#import <Foundation/Foundation.h>
@interface PodsDummy_Pods_ContentfulSeedDatabase_ContentfulPersistence : NSObject
@end
@implementation PodsDummy_Pods_ContentfulSeedDatabase_ContentfulPersistence
@end
