
// To check if a library is compiled with CocoaPods you
// can use the `COCOAPODS` macro definition which is
// defined in the xcconfigs so it is available in
// headers also when they are imported in the client
// project.


// AFNetworking
#define COCOAPODS_POD_AVAILABLE_AFNetworking
#define COCOAPODS_VERSION_MAJOR_AFNetworking 2
#define COCOAPODS_VERSION_MINOR_AFNetworking 5
#define COCOAPODS_VERSION_PATCH_AFNetworking 3

// AFNetworking/NSURLConnection
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLConnection
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLConnection 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLConnection 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLConnection 3

// AFNetworking/NSURLSession
#define COCOAPODS_POD_AVAILABLE_AFNetworking_NSURLSession
#define COCOAPODS_VERSION_MAJOR_AFNetworking_NSURLSession 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_NSURLSession 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_NSURLSession 3

// AFNetworking/Reachability
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Reachability
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Reachability 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Reachability 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Reachability 3

// AFNetworking/Security
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Security
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Security 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Security 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Security 3

// AFNetworking/Serialization
#define COCOAPODS_POD_AVAILABLE_AFNetworking_Serialization
#define COCOAPODS_VERSION_MAJOR_AFNetworking_Serialization 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_Serialization 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_Serialization 3

// AFNetworking/UIKit
#define COCOAPODS_POD_AVAILABLE_AFNetworking_UIKit
#define COCOAPODS_VERSION_MAJOR_AFNetworking_UIKit 2
#define COCOAPODS_VERSION_MINOR_AFNetworking_UIKit 5
#define COCOAPODS_VERSION_PATCH_AFNetworking_UIKit 3

// CCLRequestReplay
#define COCOAPODS_POD_AVAILABLE_CCLRequestReplay
#define COCOAPODS_VERSION_MAJOR_CCLRequestReplay 0
#define COCOAPODS_VERSION_MINOR_CCLRequestReplay 9
#define COCOAPODS_VERSION_PATCH_CCLRequestReplay 0

// CCLRequestReplay/Blueprint
#define COCOAPODS_POD_AVAILABLE_CCLRequestReplay_Blueprint
#define COCOAPODS_VERSION_MAJOR_CCLRequestReplay_Blueprint 0
#define COCOAPODS_VERSION_MINOR_CCLRequestReplay_Blueprint 9
#define COCOAPODS_VERSION_PATCH_CCLRequestReplay_Blueprint 0

// CCLRequestReplay/JSON
#define COCOAPODS_POD_AVAILABLE_CCLRequestReplay_JSON
#define COCOAPODS_VERSION_MAJOR_CCLRequestReplay_JSON 0
#define COCOAPODS_VERSION_MINOR_CCLRequestReplay_JSON 9
#define COCOAPODS_VERSION_PATCH_CCLRequestReplay_JSON 0

// CCLRequestReplay/Manager
#define COCOAPODS_POD_AVAILABLE_CCLRequestReplay_Manager
#define COCOAPODS_VERSION_MAJOR_CCLRequestReplay_Manager 0
#define COCOAPODS_VERSION_MINOR_CCLRequestReplay_Manager 9
#define COCOAPODS_VERSION_PATCH_CCLRequestReplay_Manager 0

// CCLRequestReplay/Record
#define COCOAPODS_POD_AVAILABLE_CCLRequestReplay_Record
#define COCOAPODS_VERSION_MAJOR_CCLRequestReplay_Record 0
#define COCOAPODS_VERSION_MINOR_CCLRequestReplay_Record 9
#define COCOAPODS_VERSION_PATCH_CCLRequestReplay_Record 0

// CCLRequestReplay/Replay
#define COCOAPODS_POD_AVAILABLE_CCLRequestReplay_Replay
#define COCOAPODS_VERSION_MAJOR_CCLRequestReplay_Replay 0
#define COCOAPODS_VERSION_MINOR_CCLRequestReplay_Replay 9
#define COCOAPODS_VERSION_PATCH_CCLRequestReplay_Replay 0

// ContentfulDeliveryAPI
#define COCOAPODS_POD_AVAILABLE_ContentfulDeliveryAPI
#define COCOAPODS_VERSION_MAJOR_ContentfulDeliveryAPI 1
#define COCOAPODS_VERSION_MINOR_ContentfulDeliveryAPI 9
#define COCOAPODS_VERSION_PATCH_ContentfulDeliveryAPI 2

// ContentfulPersistence
#define COCOAPODS_POD_AVAILABLE_ContentfulPersistence
#define COCOAPODS_VERSION_MAJOR_ContentfulPersistence 0
#define COCOAPODS_VERSION_MINOR_ContentfulPersistence 3
#define COCOAPODS_VERSION_PATCH_ContentfulPersistence 1

// FBSnapshotTestCase
#define COCOAPODS_POD_AVAILABLE_FBSnapshotTestCase
#define COCOAPODS_VERSION_MAJOR_FBSnapshotTestCase 1
#define COCOAPODS_VERSION_MINOR_FBSnapshotTestCase 5
#define COCOAPODS_VERSION_PATCH_FBSnapshotTestCase 0

// ISO8601DateFormatter
#define COCOAPODS_POD_AVAILABLE_ISO8601DateFormatter
#define COCOAPODS_VERSION_MAJOR_ISO8601DateFormatter 0
#define COCOAPODS_VERSION_MINOR_ISO8601DateFormatter 7
#define COCOAPODS_VERSION_PATCH_ISO8601DateFormatter 0

// OCMock
#define COCOAPODS_POD_AVAILABLE_OCMock
#define COCOAPODS_VERSION_MAJOR_OCMock 2
#define COCOAPODS_VERSION_MINOR_OCMock 2
#define COCOAPODS_VERSION_PATCH_OCMock 4

// Realm
#define COCOAPODS_POD_AVAILABLE_Realm
#define COCOAPODS_VERSION_MAJOR_Realm 0
#define COCOAPODS_VERSION_MINOR_Realm 88
#define COCOAPODS_VERSION_PATCH_Realm 0

// Realm/Headers
#define COCOAPODS_POD_AVAILABLE_Realm_Headers
#define COCOAPODS_VERSION_MAJOR_Realm_Headers 0
#define COCOAPODS_VERSION_MINOR_Realm_Headers 88
#define COCOAPODS_VERSION_PATCH_Realm_Headers 0

// VCRURLConnection
#define COCOAPODS_POD_AVAILABLE_VCRURLConnection
#define COCOAPODS_VERSION_MAJOR_VCRURLConnection 0
#define COCOAPODS_VERSION_MINOR_VCRURLConnection 2
#define COCOAPODS_VERSION_PATCH_VCRURLConnection 0

